language: c
compiler:
    - gcc-5
    - clang
branches:
    except: gh-pages
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - valgrind
        - libreadline-dev
        - libgc-dev
before_install:
    - cd ..
    - git clone http://github.com/Fedjmike/libkiss
    - cd libkiss
    - make
script:
    - make --keep-going all
