language: c
compiler:
    - clang
branches:
    except: gh-pages
addons:
    apt:
        packages:
        - valgrind
        - libreadline-dev
        - libgc-dev
before_install:
    - pushd ..
    - git clone http://github.com/Fedjmike/libkiss
    - cd libkiss
    - make
    - popd
script:
    - make --keep-going all tests
